### ISSUE TITLE
Normalized opacity?

### ISSUE THREAD

**Issue by DamienBell** [Harley-xk/MaLiang#50]
This is more of a request than an issue, but is there a technique for locking the max opacity of a stroke to a given value?
For example, say I set the brush opacity to 0.25 and the pointStep to 1. The individual samples render with an opacity of 0.25 but as they overlap it quickly goes up to 1.0. 
Do you have any ideas of how I can reliably keep the max opacity at a given value?

**Comment by Harley-xk** [comment]
Due to the current design, the opacity only effects the rendering texture, not the result content. So the only one way is to calculate the real opacity by texture size and point step:
realOpacity = (opacity property of texture) * (textureSize / pointStep)
for example, if your texture's size is 32x32, and point size is 2, you should set opacity property to (0.25/(32/2)).
I'm finding a easier way to do this :)

**Comment by DamienBell** [comment]
Thanks, that works pretty well!
